name: test_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  retrofit: 4.1.0
  equatable: ^2.0.5
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: b783000c18f6e066f3d81d5ecc352f3ce61860f6
  shared_preferences: ^2.2.3
  shared_preferences_android: ^2.2.2
  shared_preferences_ios: ^2.1.1
  get_it: ^7.7.0
  flutter_local_notifications: ^17.0.1
  flutter_bloc: ^8.1.5
  injectable: any
  json_annotation: any
  logger: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_utils: ^2.8.7
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  retrofit_generator: 8.1.0

flutter:
  uses-material-design: true

# To generate localization classes, use command: flutter pub run intl_utils:generate
# Or install Flutter Intl plugin
flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/src/ui/l10n/generated
  arb_dir: lib/src/ui/l10n