name: test_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  equatable: ^2.0.5
  workmanager: ^0.5.2
  shared_preferences: ^2.2.3
  get_it: ^7.6.9
  flutter_local_notifications: ^17.0.0
  flutter_bloc: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_utils: ^2.8.7
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

# To generate localization classes, use command: flutter pub run intl_utils:generate
# Or install Flutter Intl plugin
flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/device/localization/generated
  arb_dir: lib/device/localization